# termine, parte 1.

trigger:
    branches:
      include:        
        - master  
pool:
  vmImage: "ubuntu-16.04"

variables: 
  BuildConfiguration: 'release'
  # nombre del archivo csproj
  name-project: "mdm-cli"

steps:
  # toma todos los proyectos que existan además de quien tiene el nuget.
  - task: DotNetCoreCLI@2 
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: '$(default-feed)'      
      versioningScheme: byBuildNumber

  # genera paquete usando la versión proporcionada por gitversion
  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack' 
    inputs: 
      command: pack
      packagesToPack: '**/$(name-project).csproj'       
      arguments: '--configuration $(BuildConfiguration)'

  